### ISSUE TITLE
kwin 6 support

### ISSUE THREAD

**Issue by FuLygon** [gurrgur/kwin-effects-kinetic#1]
any chance this could get ported to support kwin 6 ?

**Comment by dgudim** [comment]
Here, I made a quick port, maybe will publish on the store
https://github.com/dgudim/themes/tree/master/kwin-effects/kinetic

**Comment by FuLygon** [comment]
> Here, I made a quick port, maybe will publish on the store https://github.com/dgudim/themes/tree/master/kwin-effects/kinetic

nice one! minimize kinetic doesn't work for me for some reason

**Comment by gurrgur** [comment]
> Here, I made a quick port, maybe will publish on the store https://github.com/dgudim/themes/tree/master/kwin-effects/kinetic

Hey there, thanks for sharing your port. I am working on an updated version with some additional tweaks myself. Feel free to publish your work but Id appreciate you using a different name and/or making it clear that it is a derivative work.

Cheers!

**Comment by dgudim** [comment]
Cool, then I'll just wait for the updated version from you to not confuse people :)

**Comment by dgudim** [comment]
@FuLygon Try again, minimize should work now

**Comment by gurrgur** [comment]
The plasma 6 port is now available, so I'll close this.

**Comment by xiota** [comment]
@gurrgurr Please tag new release.

**Comment by gurrgur** [comment]
@xiota Done. Thanks for the reminder.
